apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
  - namespace.yaml

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    version: 1.19.1
    releaseName: crossplane
