# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: "3"

includes:
  minikube:
    taskfile: clusters/minikube/taskfile.yaml
    dir: clusters/minikube
  crds:
    taskfile: crds/taskfile.yaml
    dir: crds
  argocd:
    taskfile: applications/argocd/taskfile.yaml
    dir: applications/argocd
  vault:
    taskfile: applications/vault/taskfile.yaml
    dir: applications/vault
  prometheus:
    taskfile: applications/kube-prometheus-stack/taskfile.yaml
    dir: applications/kube-prometheus-stack

tasks:
  bootstrap:
    cmds:
      - task: minikube:up
      - task: crds:install
      - task: argocd:install
      - task: vault:install
      - task: prometheus:install

  alpine: kubectl run -ti --rm alpine --image=alpine --restart=Never -- sh
