apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &namespace monitoring

resources:
  - namespace.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 72.6.2
    releaseName: prometheus
    valuesInline:
      namespace: *namespace
      cleanPrometheusOperatorObjectNames: true
      crds:
        create: false
      prometheus:
        ingress:
          enabled: true
          annotations:
            ingress.kubernetes.io/ssl-redirect: "false"
            ingress.kubernetes.io/backend-protocol: "http"
          ingressClassName: nginx
          hosts:
            - prometheus.test
        prometheusSpec:
          retention: 2d
          serviceMonitorSelectorNilUsesHelmValues: false
          podMonitorSelectorNilUsesHelmValues: false
          ruleSelectorNilUsesHelmValues: false
          probeSelectorNilUsesHelmValues: false
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
      grafana:
        ingress:
          enabled: true
          annotations:
            ingress.kubernetes.io/ssl-redirect: "false"
            ingress.kubernetes.io/backend-protocol: "http"
          ingressClassName: nginx
          hosts:
            - grafana.test
