apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    chart: gitea
    repoURL: docker.gitea.com/charts
    targetRevision: 12.0.0
    helm:
      valuesObject:
        valkey-cluster:
          enabled: false
        valkey:
          enabled: true
        postgresql:
          enabled: true
        postgresql-ha:
          enabled: false
        persistence:
          enabled: true
        gitea:
          config:
            database:
              DB_TYPE: postgres
            indexer:
              ISSUE_INDEXER_TYPE: bleve
              REPO_INDEXER_ENABLED: true
  destination:
    name: "in-cluster"
    namespace: gitea
