valkey-cluster:
  enabled: false
valkey:
  enabled: true
postgresql:
  enabled: true
postgresql-ha:
  enabled: false
persistence:
  enabled: true
gitea:
  config:
    database:
      DB_TYPE: postgres
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/backend-protocol: "http"
  className: nginx
  hosts:
    - host: gitea.test
