apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd/manifests/crds?ref=v3.0.3

helmCharts:
  - name: argo-cd
    repo: oci://ghcr.io/argoproj/argo-helm
    version: 8.0.9
    releaseName: argocd
    valuesInline:
      crds:
        install: false
      global:
        domain: argocd.test
      configs:
        cm:
          url: http://argocd.test
        params:
          server.insecure: "true"
          #server.disable.auth: "true"
      notifications:
        argocdUrl: http://argocd.test
      server:
        ingress:
          enabled: true
          ingressClassName: nginx
          host: argocd.test
          annotations:
            ingress.kubernetes.io/ssl-redirect: "false"
            ingress.kubernetes.io/backend-protocol: "http"
